version: '3'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'E_COMMERCE'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  e-commerce-backend:
    build: ./backend
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - '8080:8080'
    links:
      - db

  e-commerce-frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - e-commerce-backend

volumes:
  my-db:
