version: '3'
services:
  e-commerce-backend:
    build: ./backend
    container_name: backend
    ports:
      - '8080:8080'
    links:
      - db
      - '9000:9000'


  e-commerce-frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - e-commerce-backend