server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: e-commerce-shop
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/E_COMMERCE?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:password}
    hikari:
      initializationFailTimeout: 20000
      maximum-pool-size: 30
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_schema: E_COMMERCE
        format_sql: false
  liquibase:
    change-log: classpath:database/changelog.xml